# -*- coding: utf-8 -*-
"""python program.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NeNQfeW-5qUTy7T1RFlTfLLlRDMX74Ap
"""

#Basic 1
a=input("enter the name:")
b=int(input())

age=2024-b
print("The person",a,"born in",b,"is",age,"years old")

#basic 2
a=int(input())
if(a>80):
    print('Distinction')
elif(60<=a<=80):
    print('Pass')
elif(a<60):
    print('Fail')

#fibonacci
def fibonacci(n):
  x,y=0,1
  for i in range(n):
    print(x,end='')
    x,y=y,x+y
n=int(input())
fibonacci(n)

#display multiplication
n=int(input())
for j in range(1,11,1):
  print(n,'X',j,'=',n*j)

#palindrome
def is_palindrome(n):
    return str(n) == str(n)[::-1]

n = int(input())
if is_palindrome(n):
    print("Yes")
else:
    print("No")

#prime number
n=int(input())
for i in range(0,n):
  if i>1:
    for j in range(2,n):
      if(i%j==0):
        print(n," is prime number")
        break
    else:
      print(n," is not prime number")

#prime number
start=int(input("enter the star̥ting number\n "))
end=int(input("enter the ending number\n"))
count=0
for i in range(start,end+1):
    for j in range(2,num):
      if(i%j==0):
        break
      else:
        print(i)
        count=count+1
        break

print("total prime numbere in a given rang=",count)

#conver negative to positive
n=int(input())
positive=abs(n)
print("the positive is",positive)

#strong number
num=int(input())
summ=0
temp=num
while(num):
  i=1
  f=1
  r=num%10
  while(i<=r):
    f=f*i
    i=i+1
  summ=summ+f
  num=num//10
if(temp==summ):
  print("the number is a strong number")
else:
  print("the number is not strong number")

#armstrong number
num=int(input())
order=len(str(num))
summ=0
temp=num
while (num>0):
  r=num%10
  d=r**order
  summ=summ+d
  num=num//10
if(temp==summ):
  print("armstrong no")
else:
  print("not armstrong no")

#Neon number
num=int(input())
square=num*num
temp=num
summ=0
while(square!=0):
  r=square%10
  summ=summ+r
  square=square//10
if(temp==summ):
  print("neon number")
else:
  print("not a neon number")

#spy number
num=int(input())
temp=num
summ=0
product=1
while(num>0):
  d=num%10
  summ=summ+d
  product=product*d
  num=num//10
if(summ==product):
  print(temp,"spy number!")
else:
  print(temp,"not a spy number!")

#palindrome
a=int(input())
org=''
rev=0
while(n!=0):
  d=num%10
  rev=rev*10+d
  n=n//10
if (org==rev):
  print("palindrome")
else:
  print("not a palindrome")

#happy number
def ishappy(num):
  sum=0
  while(num!=0):
    r=num%10
    sum=sum+r**2
    num=num//10
  return sum
num=int(input())
res=num
while(res!=1 and res!=4):
  res=ishappy(res)
if(res==1):
  print("is a happy number")
elif(res==4):
  print("no")

#fibonacci
n=int(input("enter the number"))
fib1=0
fib2=1
print("Fibonacci series of a given number",n,"is")
print(fib1,fib2,end=" ")
for i in range(2,n):
  fib3=fib1+fib2
  print(fib3,end=" ")
  fib1=fib2
  fib2=fib3

#pattern1
n=int(input())
for i in range(0,5):
  for j in range(0,5):
    print("*",end=" ")
  print()

#pattern 2
n=int(input())
for i in range(0,n):
  for j in range(0,n):
    if(j<=i):
       print("*",end=" ")
  print()

#pattern 3
n=int(input())
for i in range(0,n):
  for j in range(0,n):
    if(i<=j): # i+j<=n-1
       print("*",end=" ")
  print()

#pattern 3
n=int(input())
for i in range(n):
  for j in range(n):
    if i+j>=n-1:
      print("*",end=" ")
    else:
      print(" ",end=" ")
  print()

#pattern 4
n=int(input())
for i in range(0,n):
  for j in range(0,n):
    if(j>=i):
       print("*",end=" ")
    else:
       print(" ",end=" ")
  print()

#pattern 5
n=int(input())
for i in range(0,n):
  for j in range(0,n):
    if(i>=j): #j<=i
       print(i+1,end=" ")

  print()



#pattern 6
n=int(input())
for i in range(n):
  for j in range(n):
    if i==0 or i==n-1 or j==0 or j==n-1:
        print("*",end=" ")
    else:
        print(" ",end=" ")
  print()

#pattern 7
n=int(input())
for i in range(n):
  for j in range(n):
    if i==0 or i==n-1 or j==0 or j==n-1 or i==j or i+j==n-1:
        print("*",end=" ")
    else:
        print(" ",end=" ")
  print()

#pattern 8
n-int(input())
k=input()
for i in range(n):
  for j in range(n):
    print(k,end=" ")
  print()

#pattern 9
n=int(input())
k=1
for i in range(n):
  for j in range(n):
    print(k,end=" ")
    k=k+1
  print()

#pattern 10
num = int(input("enter a number:"))
factorial=1

if num<0:
  print("sorry,factorial does not exist for negative numbers")
elif num==0:
  print("the factorial of 0 is 1")
else:
  for i in range(1,num+1):
    factorial=factorial*i
  print("the factorial of",num,"is",factorial)

#pattern 11
n=int(input())
for i in range(0,n):
  for j in range(0,n):
    if(i>=j): #j<=i
       print(j+1,end=" ")

  print()

#odd number letter
s=input()
a=""
for i in range(0,len(s)):
  if(i%2==0):
    a=a+s[i]
print(a)

#swap number
def swap_numbers(a,b):
  print("before swapping:")
  print("a=" ,a)
  print("b= ",b)
  a=a+b
  b=a-b
  a=a-b
  #temp=a   a=a+b
              #without 3rd variable feplace these three line
  #a=b                      #a=a+b b=a-b a=a-b
  #b=temp
  print("after swapping:")
  print("a= ",a)
  print("b= ",b)
  return a,b
num1=int(input())
num2=int(input())
num1,num2=swap_numbers(num1,num2)

#average number
m1=int(input())
m2=int(input())
m3=int(input())
if (m1<m2 and m1<m3):
  print(((m1+m2))/2)